version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $APP_PORT:$APP_PORT
    env_file: ./.env
    environment:      
      DB_HOST: mysqldb
      DB_HOSTNAME: mysqldb
    depends_on: 
      mysqldb: 
        condition: service_healthy
    stdin_open: true
    tty: true
    links:
      - mysqldb

  mysqldb:
    image: mysql:latest
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8]
    container_name: mysqldb
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
        - 3306:3306
    expose:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_NAME
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
volumes:
  mysql-data:

    